#!/bin/sh

DAEMON="garage-door-monitor"
PIDFILE="/var/run/$DAEMON.pid"

# shellcheck source=/dev/null
[ -r "/etc/default/$DAEMON" ] && . "/etc/default/$DAEMON"

# garage-door-monitor does not create a pidfile, so pass "-n" in the command
# line and use "-m" to instruct start-stop-daemon to create one.
start() {
        printf 'Starting %s: ' "$DAEMON"
        daemon --name "$DAEMON" --env "GARAGE_WEBHOOK=$GARAGE_WEBHOOK" \
               --pidfile "$PIDFILE" --respawn --delay 10 \
               --output "/var/log/$DAEMON.err" --command "/usr/bin/$DAEMON"
        status=$?
        if [ "$status" -eq 0 ]; then
                echo "OK"
        else
                echo "FAIL"
        fi
        return "$status"
}

stop() {
        printf 'Stopping %s: ' "$DAEMON"
        daemon --name "$DAEMON" --stop --pidfile "$PIDFILE"
        status=$?
        if [ "$status" -eq 0 ]; then
                rm -f "$PIDFILE"
                echo "OK"
        else
                echo "FAIL"
        fi
        return "$status"
}

restart() {
        printf 'Restarting %s: ' "$DAEMON"
        daemon --name "$DAEMON" --restart --pidfile "$PIDFILE"
}

case "$1" in
        start|stop|restart)
                "$1";;
        reload)
                # Restart, since there is no true "reload" feature.
                restart;;
        *)
                echo "Usage: $0 {start|stop|restart|reload}"
                exit 1
esac
